#!/bin/sh
##############################################################################
# @maintained by: EOX IT Services GmbH
# @project NGEO T4
# @version 1.0
# @date 2013-07-09
# @purpose NGEO service script for the Browse Server.
#          To be placed in /etc/init.d
##############################################################################
### BEGIN INIT INFO
# Provides: ngeo service
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $network
# Default-Start: 2 3 5
# Default-Stop: 0 1 4 6
# Short-Description: NGEO service script for the Browse Server
# Description: To start, stop, restart NGEO service Browse Server
### END INIT INFO

# ----------------------------------------------------------------------------
# Configuration section
# ----------------------------------------------------------------------------

# Subsystem name
SUBSYSTEM="ngEO Browse Server"

# ----------------------------------------------------------------------------
# End of configuration section
# ----------------------------------------------------------------------------

# ----------------------------------------------------------------------------
# Start
# ----------------------------------------------------------------------------
ngeo_start() {
    echo "------------------------------------------------------------------------------"
    echo " $SUBSYSTEM Service Start"
    echo "------------------------------------------------------------------------------"
    service postgresql start
    service memcached start
    #make sure postgresql is accepting connections before starting httpd
    #timeout after 20 attempts
    i="0"
    while [ $i -lt 20 ]; do
        response=`su - postgres -c -- 'psql -U postgres -t  -c "select now()" postgres'`
        if [ $? -eq 0 ]; then
            break
        fi
        sleep 1
        i=$[$i+1]
    done
    if [ $i -eq 20 ]; then
        echo "ERROR: Couldn't connect to PostgreSQL server"
        exit 1
    fi
    service httpd start
}

# ----------------------------------------------------------------------------
# Stop
# ----------------------------------------------------------------------------
ngeo_stop() {
    echo "------------------------------------------------------------------------------"
    echo " $SUBSYSTEM Service Stop"
    echo "------------------------------------------------------------------------------"
    service httpd stop
    service memcached stop
    service postgresql stop
}

# ----------------------------------------------------------------------------
# Status
# ----------------------------------------------------------------------------
ngeo_status() {
    echo -n "Checking for service ${MYSELF}:"
    service postgresql status
    service httpd status
    service memcached status
}

# ----------------------------------------------------------------------------
# Clean locks
# ----------------------------------------------------------------------------
ngeo_cleanlocks() {
    rm -f /var/www/ngeo/ngeo_browse_server_instance/ngeo_browse_server_instance/conf/status.conf.lck
    rm -f /var/www/ngeo/ngeo_browse_server_instance/ngeo_browse_server_instance/conf/controller.conf.lck
    rm -f /var/www/ngeo/ngeo_browse_server_instance/ngeo_browse_server_instance/mapcache.xml.lck
    rm -f /var/www/ngeo/ngeo_browse_server_instance/ngeo_browse_server_instance/mapcache_seed.lck
}

# ----------------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------------
case "$1" in
start)
    ngeo_cleanlocks
    ngeo_start
    ngeo_status
;;
stop)
    ngeo_stop
    ngeo_cleanlocks
;;
restart)
    ngeo_stop
    ngeo_cleanlocks
    ngeo_start
    ngeo_status
;;
status)
    ngeo_status
;;
*)
    echo "Usage: $0 {start|stop|restart|status}"
exit 1
;;
esac

# END ########################################################################
